version: '3.8'
services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile-render
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=asker123
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql

volumes:
  mssql-data:
