services:
  - type: web
    name: webtestui-backend
    env: docker
    region: oregon
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: webtestui-postgres-db
          property: connectionString
      - key: UsePostgreSQL
        value: true
      - key: JWT__Key
        generateValue: true
  
  - type: postgres
    name: webtestui-postgres-db
    region: oregon
    plan: free
    ipAllowList: []
