CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetUsers" (
    "Id" text NOT NULL,
    "Name" text,
    "ProfileImageBase64" text,
    "Phone" text,
    "Address" text,
    "Website" text,
    "TwoFactorEnabled" boolean NOT NULL,
    "TwoFactorCode" text,
    "TwoFactorCodeExpiry" timestamp with time zone,
    "Language" text,
    "Timezone" text,
    "DateFormat" text,
    "AutoLogoutEnabled" boolean,
    "SessionTimeoutMinutes" integer,
    "Theme" text,
    "CompactViewEnabled" boolean,
    "ShowSidebarEnabled" boolean,
    "UsageAnalyticsEnabled" boolean,
    "CrashReportsEnabled" boolean,
    "MarketingEmailsEnabled" boolean,
    "CreatedAt" timestamp with time zone NOT NULL,
    "LastLogin" timestamp with time zone,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

CREATE TABLE "Faqs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Question" character varying(250) NOT NULL,
    "Answer" text NOT NULL,
    "Category" character varying(50) NOT NULL,
    "SortOrder" integer NOT NULL,
    "IsPublished" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Faqs" PRIMARY KEY ("Id")
);

CREATE TABLE "HelpDocuments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" character varying(200) NOT NULL,
    "Content" text NOT NULL,
    "Category" character varying(50) NOT NULL,
    "Description" character varying(500) NOT NULL,
    "IconName" text NOT NULL,
    "SortOrder" integer NOT NULL,
    "IsPublished" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_HelpDocuments" PRIMARY KEY ("Id")
);

CREATE TABLE "K6Tests" (
    "Id" uuid NOT NULL,
    "Name" text NOT NULL,
    "Description" text,
    "Script" text NOT NULL,
    "AuthType" text,
    "AuthToken" text,
    "Options" jsonb,
    "Logs" jsonb,
    "ErrorDetails" jsonb,
    "RequestId" integer,
    "Status" text NOT NULL,
    "Results" jsonb,
    "ProcessId" integer,
    "CreatedAt" bigint NOT NULL,
    "UpdatedAt" bigint NOT NULL,
    CONSTRAINT "PK_K6Tests" PRIMARY KEY ("Id")
);

CREATE TABLE "SharedData" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ShareId" character varying(255) NOT NULL,
    "DataJson" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ExpiresAt" timestamp with time zone,
    CONSTRAINT "PK_SharedData" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ChatMessages" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Content" text NOT NULL,
    "UserId" text NOT NULL,
    "IsFromUser" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "SessionId" text NOT NULL,
    "ModelResponse" text,
    "ModelType" character varying(50),
    CONSTRAINT "PK_ChatMessages" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ChatMessages_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Environments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text,
    "Name" text,
    "IsActive" boolean NOT NULL,
    "Variables" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Environments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Environments_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "NotificationPreferences" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ApiUpdatesEnabled" boolean NOT NULL,
    "RequestErrorsEnabled" boolean NOT NULL,
    "TestFailuresEnabled" boolean NOT NULL,
    "MentionsEnabled" boolean NOT NULL,
    "EmailCommentsEnabled" boolean NOT NULL,
    "EmailSharedApisEnabled" boolean NOT NULL,
    "EmailSecurityAlertsEnabled" boolean NOT NULL,
    "NewsletterEnabled" boolean NOT NULL,
    "SlackEnabled" boolean NOT NULL,
    "DiscordEnabled" boolean NOT NULL,
    "SlackWebhookUrl" text,
    "SlackChannel" text,
    "DiscordWebhookUrl" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_NotificationPreferences" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_NotificationPreferences_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Notifications" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "Title" text NOT NULL,
    "Message" text NOT NULL,
    "Type" text NOT NULL,
    "RelatedEntityType" text,
    "RelatedEntityId" integer,
    "IsRead" boolean NOT NULL,
    "IsArchived" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Notifications_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "SupportTickets" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Subject" character varying(200) NOT NULL,
    "Message" text NOT NULL,
    "UserId" text NOT NULL,
    "Status" text NOT NULL,
    "Priority" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_SupportTickets" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SupportTickets_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Collections" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text,
    "Name" text,
    "Description" text,
    "EnvironmentId" integer,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Collections" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Collections_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Collections_Environments_EnvironmentId" FOREIGN KEY ("EnvironmentId") REFERENCES "Environments" ("Id")
);

CREATE TABLE "SupportTicketReplies" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Message" text NOT NULL,
    "TicketId" integer NOT NULL,
    "UserId" text NOT NULL,
    "IsFromSupport" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_SupportTicketReplies" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SupportTicketReplies_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id"),
    CONSTRAINT "FK_SupportTicketReplies_SupportTickets_TicketId" FOREIGN KEY ("TicketId") REFERENCES "SupportTickets" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Requests" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text,
    "CollectionId" integer,
    "EnvironmentId" integer,
    "Name" text,
    "Description" text,
    "Method" text,
    "Url" text,
    "Headers" text,
    "AuthType" text,
    "AuthConfig" text,
    "Params" text,
    "Body" text,
    "Tests" text,
    "IsFavorite" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Requests" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Requests_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Requests_Collections_CollectionId" FOREIGN KEY ("CollectionId") REFERENCES "Collections" ("Id"),
    CONSTRAINT "FK_Requests_Environments_EnvironmentId" FOREIGN KEY ("EnvironmentId") REFERENCES "Environments" ("Id")
);

CREATE TABLE "HistoryEntries" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text,
    "RequestId" integer,
    "EnvironmentId" integer,
    "Method" text,
    "Url" text,
    "Status" integer,
    "Duration" integer,
    "ResponseSize" integer,
    "Timestamp" timestamp with time zone NOT NULL,
    "Response" text,
    "RequestHeaders" text,
    "RequestBody" text,
    CONSTRAINT "PK_HistoryEntries" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_HistoryEntries_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id"),
    CONSTRAINT "FK_HistoryEntries_Environments_EnvironmentId" FOREIGN KEY ("EnvironmentId") REFERENCES "Environments" ("Id"),
    CONSTRAINT "FK_HistoryEntries_Requests_RequestId" FOREIGN KEY ("RequestId") REFERENCES "Requests" ("Id")
);

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

CREATE INDEX "IX_ChatMessages_UserId" ON "ChatMessages" ("UserId");

CREATE INDEX "IX_Collections_EnvironmentId" ON "Collections" ("EnvironmentId");

CREATE INDEX "IX_Collections_UserId" ON "Collections" ("UserId");

CREATE INDEX "IX_Environments_UserId" ON "Environments" ("UserId");

CREATE INDEX "IX_HistoryEntries_EnvironmentId" ON "HistoryEntries" ("EnvironmentId");

CREATE INDEX "IX_HistoryEntries_RequestId" ON "HistoryEntries" ("RequestId");

CREATE INDEX "IX_HistoryEntries_UserId" ON "HistoryEntries" ("UserId");

CREATE UNIQUE INDEX "IX_NotificationPreferences_UserId" ON "NotificationPreferences" ("UserId");

CREATE INDEX "IX_Notifications_UserId" ON "Notifications" ("UserId");

CREATE INDEX "IX_Requests_CollectionId" ON "Requests" ("CollectionId");

CREATE INDEX "IX_Requests_EnvironmentId" ON "Requests" ("EnvironmentId");

CREATE INDEX "IX_Requests_UserId" ON "Requests" ("UserId");

CREATE INDEX "IX_SupportTicketReplies_TicketId" ON "SupportTicketReplies" ("TicketId");

CREATE INDEX "IX_SupportTicketReplies_UserId" ON "SupportTicketReplies" ("UserId");

CREATE INDEX "IX_SupportTickets_UserId" ON "SupportTickets" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250509133347_InitialPostgreSQL', '8.0.4');

COMMIT;

START TRANSACTION;

ALTER TABLE "ChatMessages" DROP CONSTRAINT "FK_ChatMessages_AspNetUsers_UserId";

ALTER TABLE "Collections" DROP CONSTRAINT "FK_Collections_AspNetUsers_UserId";

ALTER TABLE "Collections" DROP CONSTRAINT "FK_Collections_Environments_EnvironmentId";

ALTER TABLE "Environments" DROP CONSTRAINT "FK_Environments_AspNetUsers_UserId";

ALTER TABLE "HistoryEntries" DROP CONSTRAINT "FK_HistoryEntries_AspNetUsers_UserId";

ALTER TABLE "HistoryEntries" DROP CONSTRAINT "FK_HistoryEntries_Environments_EnvironmentId";

ALTER TABLE "HistoryEntries" DROP CONSTRAINT "FK_HistoryEntries_Requests_RequestId";

ALTER TABLE "NotificationPreferences" DROP CONSTRAINT "FK_NotificationPreferences_AspNetUsers_UserId";

ALTER TABLE "Notifications" DROP CONSTRAINT "FK_Notifications_AspNetUsers_UserId";

ALTER TABLE "Requests" DROP CONSTRAINT "FK_Requests_AspNetUsers_UserId";

ALTER TABLE "Requests" DROP CONSTRAINT "FK_Requests_Collections_CollectionId";

ALTER TABLE "Requests" DROP CONSTRAINT "FK_Requests_Environments_EnvironmentId";

ALTER TABLE "SupportTicketReplies" DROP CONSTRAINT "FK_SupportTicketReplies_AspNetUsers_UserId";

ALTER TABLE "SupportTicketReplies" DROP CONSTRAINT "FK_SupportTicketReplies_SupportTickets_TicketId";

ALTER TABLE "SupportTickets" DROP CONSTRAINT "FK_SupportTickets_AspNetUsers_UserId";

ALTER TABLE "Requests" DROP CONSTRAINT "PK_Requests";

ALTER TABLE "Notifications" DROP CONSTRAINT "PK_Notifications";

ALTER TABLE "Faqs" DROP CONSTRAINT "PK_Faqs";

ALTER TABLE "Environments" DROP CONSTRAINT "PK_Environments";

ALTER TABLE "Collections" DROP CONSTRAINT "PK_Collections";

ALTER TABLE "SupportTickets" DROP CONSTRAINT "PK_SupportTickets";

ALTER TABLE "SupportTicketReplies" DROP CONSTRAINT "PK_SupportTicketReplies";

ALTER TABLE "SharedData" DROP CONSTRAINT "PK_SharedData";

ALTER TABLE "NotificationPreferences" DROP CONSTRAINT "PK_NotificationPreferences";

ALTER TABLE "K6Tests" DROP CONSTRAINT "PK_K6Tests";

ALTER TABLE "HistoryEntries" DROP CONSTRAINT "PK_HistoryEntries";

ALTER TABLE "HelpDocuments" DROP CONSTRAINT "PK_HelpDocuments";

ALTER TABLE "ChatMessages" DROP CONSTRAINT "PK_ChatMessages";

ALTER TABLE "Requests" RENAME TO requests;

ALTER TABLE "Notifications" RENAME TO notifications;

ALTER TABLE "Faqs" RENAME TO faqs;

ALTER TABLE "Environments" RENAME TO environments;

ALTER TABLE "Collections" RENAME TO collections;

ALTER TABLE "SupportTickets" RENAME TO support_tickets;

ALTER TABLE "SupportTicketReplies" RENAME TO support_ticket_replies;

ALTER TABLE "SharedData" RENAME TO shared_data;

ALTER TABLE "NotificationPreferences" RENAME TO notification_preferences;

ALTER TABLE "K6Tests" RENAME TO k6_tests;

ALTER TABLE "HistoryEntries" RENAME TO history_entries;

ALTER TABLE "HelpDocuments" RENAME TO help_documents;

ALTER TABLE "ChatMessages" RENAME TO chat_messages;

ALTER INDEX "IX_Requests_UserId" RENAME TO "IX_requests_UserId";

ALTER INDEX "IX_Requests_EnvironmentId" RENAME TO "IX_requests_EnvironmentId";

ALTER INDEX "IX_Requests_CollectionId" RENAME TO "IX_requests_CollectionId";

ALTER INDEX "IX_Notifications_UserId" RENAME TO "IX_notifications_UserId";

ALTER INDEX "IX_Environments_UserId" RENAME TO "IX_environments_UserId";

ALTER INDEX "IX_Collections_UserId" RENAME TO "IX_collections_UserId";

ALTER INDEX "IX_Collections_EnvironmentId" RENAME TO "IX_collections_EnvironmentId";

ALTER INDEX "IX_SupportTickets_UserId" RENAME TO "IX_support_tickets_UserId";

ALTER INDEX "IX_SupportTicketReplies_UserId" RENAME TO "IX_support_ticket_replies_UserId";

ALTER INDEX "IX_SupportTicketReplies_TicketId" RENAME TO "IX_support_ticket_replies_TicketId";

ALTER INDEX "IX_NotificationPreferences_UserId" RENAME TO "IX_notification_preferences_UserId";

ALTER INDEX "IX_HistoryEntries_UserId" RENAME TO "IX_history_entries_UserId";

ALTER INDEX "IX_HistoryEntries_RequestId" RENAME TO "IX_history_entries_RequestId";

ALTER INDEX "IX_HistoryEntries_EnvironmentId" RENAME TO "IX_history_entries_EnvironmentId";

ALTER INDEX "IX_ChatMessages_UserId" RENAME TO "IX_chat_messages_UserId";

ALTER TABLE requests ADD CONSTRAINT "PK_requests" PRIMARY KEY ("Id");

ALTER TABLE notifications ADD CONSTRAINT "PK_notifications" PRIMARY KEY ("Id");

ALTER TABLE faqs ADD CONSTRAINT "PK_faqs" PRIMARY KEY ("Id");

ALTER TABLE environments ADD CONSTRAINT "PK_environments" PRIMARY KEY ("Id");

ALTER TABLE collections ADD CONSTRAINT "PK_collections" PRIMARY KEY ("Id");

ALTER TABLE support_tickets ADD CONSTRAINT "PK_support_tickets" PRIMARY KEY ("Id");

ALTER TABLE support_ticket_replies ADD CONSTRAINT "PK_support_ticket_replies" PRIMARY KEY ("Id");

ALTER TABLE shared_data ADD CONSTRAINT "PK_shared_data" PRIMARY KEY ("Id");

ALTER TABLE notification_preferences ADD CONSTRAINT "PK_notification_preferences" PRIMARY KEY ("Id");

ALTER TABLE k6_tests ADD CONSTRAINT "PK_k6_tests" PRIMARY KEY ("Id");

ALTER TABLE history_entries ADD CONSTRAINT "PK_history_entries" PRIMARY KEY ("Id");

ALTER TABLE help_documents ADD CONSTRAINT "PK_help_documents" PRIMARY KEY ("Id");

ALTER TABLE chat_messages ADD CONSTRAINT "PK_chat_messages" PRIMARY KEY ("Id");

ALTER TABLE chat_messages ADD CONSTRAINT "FK_chat_messages_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE;

ALTER TABLE collections ADD CONSTRAINT "FK_collections_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE;

ALTER TABLE collections ADD CONSTRAINT "FK_collections_environments_EnvironmentId" FOREIGN KEY ("EnvironmentId") REFERENCES environments ("Id");

ALTER TABLE environments ADD CONSTRAINT "FK_environments_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE;

ALTER TABLE history_entries ADD CONSTRAINT "FK_history_entries_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id");

ALTER TABLE history_entries ADD CONSTRAINT "FK_history_entries_environments_EnvironmentId" FOREIGN KEY ("EnvironmentId") REFERENCES environments ("Id");

ALTER TABLE history_entries ADD CONSTRAINT "FK_history_entries_requests_RequestId" FOREIGN KEY ("RequestId") REFERENCES requests ("Id");

ALTER TABLE notification_preferences ADD CONSTRAINT "FK_notification_preferences_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE;

ALTER TABLE notifications ADD CONSTRAINT "FK_notifications_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE;

ALTER TABLE requests ADD CONSTRAINT "FK_requests_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE;

ALTER TABLE requests ADD CONSTRAINT "FK_requests_collections_CollectionId" FOREIGN KEY ("CollectionId") REFERENCES collections ("Id");

ALTER TABLE requests ADD CONSTRAINT "FK_requests_environments_EnvironmentId" FOREIGN KEY ("EnvironmentId") REFERENCES environments ("Id");

ALTER TABLE support_ticket_replies ADD CONSTRAINT "FK_support_ticket_replies_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id");

ALTER TABLE support_ticket_replies ADD CONSTRAINT "FK_support_ticket_replies_support_tickets_TicketId" FOREIGN KEY ("TicketId") REFERENCES support_tickets ("Id") ON DELETE CASCADE;

ALTER TABLE support_tickets ADD CONSTRAINT "FK_support_tickets_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250509141206_PostgreSQLMigration', '8.0.4');

COMMIT;

